### ISSUE TITLE
More Efficient Listener Adding

### ISSUE THREAD

**Issue by JudeAsterix** [elParcero/calculator#1]
https://github.com/elParcero/calculator/blob/8b0bc1785263f5dae1c2a18a002a435c29d94678/P5DIAZ/src/p5diaz/WindowBuilder.java#L126-L152

It's best just to add the appropriate ActionListener to each button individually.

**Comment by elParcero** [comment]
Suggestion has been taken into consideration and changes have been made accordingly. Thank you for your advice.
